#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 6.2
#  in conjunction with Tcl version 8.6
#    Sep 16, 2021 01:59:13 PM IST  platform: Windows NT

import sys
from tkinter import font
try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import def_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Toplevel1 (root)
    def_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_Toplevel1(root, *args, **kwargs)' .'''
    global w, w_win, root
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    top = Toplevel1 (w)
    def_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#ffffff'  # X11 color: 'white'
        _fgcolor = '#000000'  # Closest X11 color: 'DodgerBlue2'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("679x450+244+101")
        top.minsize(120, 1)
        top.maxsize(1370, 749)
        top.resizable(0,  0)
        top.title("New Toplevel")
        top.configure(background="#ffffff")
        import ctypes
        
        from BlurWindow.blurWindow import blur,Win7Blur,GlobalBlur

        top.config(bg='lightblue')

        top.wm_attributes("-transparent",'' )
        top.geometry('500x400')
        top.update()
        
        HWND = ctypes.windll.user32.GetForegroundWindow()
        GlobalBlur(HWND,hexColor="#ffffff20",Acrylic=True)
        Win7Blur(HWND,Acrylic=False)
        
        self.Canvas1 = tk.Canvas(top)
        self.Canvas1.place(x=120, y=0, height=453, width=557)
        self.Canvas1.configure(background="#ffffff")
        self.Canvas1.configure(borderwidth="2")
        self.Canvas1.configure(cursor="fleur")
        self.Canvas1.configure(highlightbackground="#ffffff")
        self.Canvas1.configure(insertbackground="white")
        self.Canvas1.configure(relief="ridge")
        self.Canvas1.configure(selectbackground="blue")
        self.Canvas1.configure(selectforeground="white")

        self.menubar = tk.Menu(top,font="TkMenuFont",bg=_bgcolor,fg='#2781ed')
        top.configure(menu = self.menubar)

        self.Frame1 = tk.Frame(top)
        self.Frame1.place(x=0, y=0, height=455, width=125)
        self.Frame1.configure(relief='groove')
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief="flat")
        self.Frame1.configure(background="#111111")

        self.Button1 = tk.Button(self.Frame1)
        self.Button1.place(x=0, y=30, height=34, width=127)
        self.Button1.configure(activebackground="#ececec")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#111111")
        self.Button1.configure(disabledforeground="#bfbfbf")
        self.Button1.configure(foreground="black")
        self.Button1.configure(highlightbackground="#ffffff")
        self.Button1.configure(highlightcolor="white")
        self.Button1.configure(pady="0")
        self.Button1.configure(relief="flat")
        self.Button1.configure(text='''Button''')
        buttonFont = font.Font(family='Helvetica', size=16, weight='bold')
        self.Button1.configure(font=buttonFont)

        self.Button2 = tk.Button(self.Frame1)
        self.Button2.place(x=0, y=110, height=34, width=127)
        self.Button2.configure(activebackground="#ececec")
        self.Button2.configure(activeforeground="#000000")
        self.Button2.configure(background="#111111")
        self.Button2.configure(disabledforeground="#bfbfbf")
        self.Button2.configure(foreground="black")
        self.Button2.configure(highlightbackground="#ffffff")
        self.Button2.configure(highlightcolor="white")
        self.Button2.configure(overrelief="ridge")
        self.Button2.configure(pady="0")
        self.Button2.configure(relief="flat")
        self.Button2.configure(text='''Button''')

        self.Button3 = tk.Button(self.Frame1)
        self.Button3.place(x=0, y=70, height=34, width=127)
        self.Button3.configure(activebackground="#ececec")
        self.Button3.configure(activeforeground="#000000")
        self.Button3.configure(background="#111111")
        self.Button3.configure(disabledforeground="#bfbfbf")
        self.Button3.configure(foreground="black")
        self.Button3.configure(highlightbackground="#ffffff")
        self.Button3.configure(highlightcolor="white")
        self.Button3.configure(pady="0")
        self.Button3.configure(relief="flat")
        self.Button3.configure(text='''Button''')

        self.Button4 = tk.Button(self.Frame1)
        self.Button4.place(x=-560, y=230, height=34, width=127)
        self.Button4.configure(activebackground="#ececec")
        self.Button4.configure(activeforeground="#000000")
        self.Button4.configure(background="#111111")
        self.Button4.configure(disabledforeground="#bfbfbf")
        self.Button4.configure(foreground="black")
        self.Button4.configure(highlightbackground="#ffffff")
        self.Button4.configure(highlightcolor="white")
        self.Button4.configure(pady="0")
        self.Button4.configure(relief="flat")
        self.Button4.configure(text='''Button''')

        self.Label1 = tk.Label(self.Frame1)
        self.Label1.place(x=0, y=0, height=31, width=124)
        self.Label1.configure(background="#111111")
        self.Label1.configure(disabledforeground="#bfbfbf")
        self.Label1.configure(foreground="black")
        self.Label1.configure(text='''Label''')

if __name__ == '__main__':
    vp_start_gui()





