#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 6.2
#  in conjunction with Tcl version 8.6
#    Sep 22, 2021 05:34:44 AM IST  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import kk_support
import os.path
window_width, window_height = 0,0
def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root, top
    global prog_location
    prog_call = sys.argv[0]
    prog_location = os.path.split(prog_call)[0]
    root = tk.Tk()
    top = Toplevel1 (root)
    root.bind("<Configure>", resize)
    
    kk_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_Toplevel1(root, *args, **kwargs)' .'''
    global w, w_win, root
    global prog_location
    prog_call = sys.argv[0]
    prog_location = os.path.split(prog_call)[0]
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    top = Toplevel1 (w)
    kk_support.init(w, top, *args, **kwargs)
    return (w, top)
def resize(event):
    #print('res',event.widget.widgetName)
    global window_width, window_height
    if hasattr(event.widget,'widgetName'):
        if event.widget.widgetName == "frame":
            if (window_width != event.width) and (window_height != event.height):
                window_width, window_height = event.width,event.height
                print(f"The width of Toplevel is {window_width} and the height of Toplevel "
                    f"is {window_height}")
                if window_width >= 98:
                    print(window_width)
                    top.Labelk.grid(row=1, column=1, columnspan=1,padx=60,pady=20)
                    top.Labelk2 = tk.Label(top.Frame1)
                    top.Labelk2.configure(foreground="#0080ff",background="#ffffff")
                    top.Labelk2.configure(text='''FaceMesh''')
                    top.Labelk2.grid(row=2, column=1, columnspan=1,padx=20,pady=20)
        
                else:
                    top.Labelk.grid_remove()
                    top.Labelk2.grid_remove()
                    
        
def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#ffffff'  # X11 color: 'white'
        _fgcolor = '#0080ff'  # Closest X11 color: 'DodgerBlue2'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("682x450+330+84")
        top.minsize(120, 1)
        top.maxsize(1370, 749)
        top.resizable(1,  1)
        top.title("New Toplevel")
        top.configure(background="#dadada")
        top.configure(highlightbackground="#ffffff")
        top.configure(highlightcolor="black")

        self.Frame1 = tk.Frame(top)
        self.Frame1.place(relx=0.0, rely=0.0, relheight=1.011, relwidth=0.085)
        self.Frame1.configure(relief='flat')
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(background="#ffffff")
        self.Frame1.configure(highlightbackground="#ffffff")
        self.Frame1.configure(highlightcolor="black")

        self.Label1 = tk.Label(self.Frame1)
        self.Label1.place(relx=-6.0, rely=0.088, height=61, width=48)
        self.Label1.configure(activebackground="#ffffff")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(background="#ffffff")
        self.Label1.configure(disabledforeground="#bfbfbf")
        self.Label1.configure(foreground="#0080ff")
        self.Label1.configure(highlightbackground="#ffffff")
        self.Label1.configure(highlightcolor="black")
        photo_location = os.path.join(prog_location,"images/icons8-face-id-40.png")
        global _img0
        _img0 = tk.PhotoImage(file=photo_location)
        self.Label1.configure(image=_img0)
        self.Label1.configure(text='''Label''')
        
        self.Labelk = tk.Label(self.Frame1)
        self.Labelk.configure(foreground="#0080ff",background="#ffffff")
        self.Labelk.configure(text='''Menu''')
        
        self.Label2 = tk.Label(self.Frame1)
        self.Label2.place(relx=0.0, rely=0.013, height=41, width=57)
        self.Label2.configure(activebackground="#ffffff")
        self.Label2.configure(activeforeground="black")
        self.Label2.configure(background="#ffffff")
        self.Label2.configure(disabledforeground="#bfbfbf")
        self.Label2.configure(foreground="#0080ff")
        self.Label2.configure(highlightbackground="#ffffff")
        self.Label2.configure(highlightcolor="black")
        photo_location = os.path.join(prog_location,"images/icons8-menu-40.png")
        global _img1
        _img1 = tk.PhotoImage(file=photo_location)
        self.Label2.configure(image=_img1)
        self.Label2.configure(text='''Label''')

        self.Label3 = tk.Label(self.Frame1)
        self.Label3.place(relx=-1.276, rely=0.505, height=61, width=48)
        self.Label3.configure(activebackground="#ffffff")
        self.Label3.configure(activeforeground="black")
        self.Label3.configure(background="#ffffff")
        self.Label3.configure(disabledforeground="#bfbfbf")
        self.Label3.configure(foreground="#0080ff")
        self.Label3.configure(highlightbackground="#ffffff")
        self.Label3.configure(highlightcolor="black")
        self.Label3.configure(text='''Label''')

        self.Label4 = tk.Label(self.Frame1)
        self.Label4.place(relx=0.0, rely=0.879, height=51, width=58)
        self.Label4.configure(activebackground="#ffffff")
        self.Label4.configure(activeforeground="black")
        self.Label4.configure(background="#ffffff")
        self.Label4.configure(disabledforeground="#bfbfbf")
        self.Label4.configure(foreground="#0080ff")
        self.Label4.configure(highlightbackground="#ffffff")
        self.Label4.configure(highlightcolor="black")
        self.Label4.configure(text='''Apple''')

        self.Label5 = tk.Label(self.Frame1)
        self.Label5.place(relx=0.0, rely=0.099, height=51, width=57)
        self.Label5.configure(activebackground="#ffffff")
        self.Label5.configure(activeforeground="black")
        self.Label5.configure(background="#ffffff")
        self.Label5.configure(disabledforeground="#bfbfbf")
        self.Label5.configure(foreground="#0080ff")
        self.Label5.configure(highlightbackground="#ffffff")
        self.Label5.configure(highlightcolor="black")
        photo_location = os.path.join(prog_location,"images/icons8-face-id-40.png")
        global _img2
        _img2 = tk.PhotoImage(file=photo_location)
        self.Label5.configure(image=_img2)
        self.Label5.configure(text='''Label''')

        self.Label6 = tk.Label(self.Frame1)
        self.Label6.place(relx=0.0, rely=0.785, height=54, width=56)
        self.Label6.configure(activebackground="#ffffff")
        self.Label6.configure(activeforeground="black")
        self.Label6.configure(background="#ffffff")
        self.Label6.configure(disabledforeground="#bfbfbf")
        self.Label6.configure(foreground="#0080ff")
        self.Label6.configure(highlightbackground="#ffffff")
        self.Label6.configure(highlightcolor="black")
        photo_location = os.path.join(prog_location,"images/icons8-exit-40.png")
        global _img3
        _img3 = tk.PhotoImage(file=photo_location)
        self.Label6.configure(image=_img3)
        self.Label6.configure(text='''Label''')

if __name__ == '__main__':
    vp_start_gui()





