#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 6.2
#  in conjunction with Tcl version 8.6
#    Sep 28, 2021 06:44:09 PM IST  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import testmenu_support
import os.path

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    global prog_location
    prog_call = sys.argv[0]
    prog_location = os.path.split(prog_call)[0]
    root = tk.Tk()
    top = Toplevel1 (root)
    testmenu_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_Toplevel1(root, *args, **kwargs)' .'''
    global w, w_win, root
    global prog_location
    prog_call = sys.argv[0]
    prog_location = os.path.split(prog_call)[0]
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    top = Toplevel1 (w)
    testmenu_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#ffffff'  # X11 color: 'white'
        _fgcolor = '#0080ff'  # Closest X11 color: 'DodgerBlue2'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("600x450")
        top.minsize(120, 1)
        top.maxsize(1370, 749)
        top.resizable(0,  0)
        top.title("New Toplevel")
        top.configure(background="#1e1e1e")

        self.menubar = tk.Menu(top,font="TkMenuFont",bg='#000000',fg='#ffffff')
        top.configure(menu = self.menubar)

        self.Frame1 = tk.Frame(top)
        self.Frame1.place(x=0, y=0, height=35, width=1365)
        self.Frame1.configure(relief='flat')
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(background="#171717")

        self.Label2 = tk.Label(self.Frame1)
        self.Label2.place(x=-360, y=-50, height=41, width=34)
        self.Label2.configure(background="#252525")
        self.Label2.configure(disabledforeground="#bfbfbf")
        self.Label2.configure(foreground="#0080ff")
        photo_location = os.path.join(prog_location,"../Downloads/icons8-apple-logo-24.png")
        global _img0
        _img0 = tk.PhotoImage(file=photo_location)
        self.Label2.configure(image=_img0)

        self.Button1 = tk.Button(self.Frame1)
        self.Button1.place(x=50, y=-10, height=54, width=57)
        self.Button1.configure(activebackground="#333333")
        self.Button1.configure(activeforeground="white")
        self.Button1.configure(activeforeground="#ffffff")
        self.Button1.configure(background="#171717")
        self.Button1.configure(borderwidth="0")
        self.Button1.configure(cursor="hand2")
        self.Button1.configure(disabledforeground="#bfbfbf")
        self.Button1.configure(foreground="#ffffff")
        self.Button1.configure(highlightbackground="#c0c0c0")
        self.Button1.configure(highlightcolor="#c0c0c0")
        self.Button1.configure(highlightthickness="0")
        self.Button1.configure(overrelief="flat")
        self.Button1.configure(pady="0")
        self.Button1.configure(relief="flat")
        self.Button1.configure(text='''Menu''')

        self.Label1 = tk.Label(self.Frame1)
        self.Label1.place(x=110, y=-10, height=51, width=44)
        self.Label1.configure(activebackground="#171717")
        self.Label1.configure(activeforeground="white")
        self.Label1.configure(activeforeground="#ffffff")
        self.Label1.configure(background="#171717")
        self.Label1.configure(disabledforeground="#bfbfbf")
        self.Label1.configure(font="-family {Segoe UI} -size 6")
        self.Label1.configure(foreground="#c0c0c0")
        self.Label1.configure(text='''v1.0.0''')

        self.Label3 = tk.Label(self.Frame1)
        self.Label3.place(x=0, y=-10, height=51, width=44)
        self.Label3.configure(background="#2e2e2e")
        self.Label3.configure(disabledforeground="#bfbfbf")
        self.Label3.configure(foreground="#0080ff")
        photo_location = os.path.join(prog_location,"../Downloads/icons8-apple-logo-24.png")
        global _img1
        _img1 = tk.PhotoImage(file=photo_location)
        self.Label3.configure(image=_img1)
        self.Label3.configure(text='''Label''')

    @staticmethod
    def popup1(event, *args, **kwargs):
        Popupmenu1 = tk.Menu(root, tearoff=0)
        Popupmenu1.configure(activebackground="#ececec")
        Popupmenu1.configure(activeborderwidth="1")
        Popupmenu1.configure(activeforeground="#0080ff")
        Popupmenu1.configure(background="#ffffff")
        Popupmenu1.configure(borderwidth="1")
        Popupmenu1.configure(disabledforeground="#bfbfbf")
        Popupmenu1.configure(foreground="#0080ff")
        Popupmenu1.post(event.x_root, event.y_root)

    @staticmethod
    def popup2(event, *args, **kwargs):
        Popupmenu2 = tk.Menu(root, tearoff=0)
        Popupmenu2.configure(activebackground="#ececec")
        Popupmenu2.configure(activeborderwidth="1")
        Popupmenu2.configure(activeforeground="#0080ff")
        Popupmenu2.configure(background="#ffffff")
        Popupmenu2.configure(borderwidth="1")
        Popupmenu2.configure(disabledforeground="#bfbfbf")
        Popupmenu2.configure(foreground="#0080ff")
        Popupmenu2.post(event.x_root, event.y_root)

    @staticmethod
    def popup3(event, *args, **kwargs):
        Popupmenu3 = tk.Menu(root, tearoff=0)
        Popupmenu3.configure(activebackground="#ececec")
        Popupmenu3.configure(activeborderwidth="1")
        Popupmenu3.configure(activeforeground="#0080ff")
        Popupmenu3.configure(background="#ffffff")
        Popupmenu3.configure(borderwidth="1")
        Popupmenu3.configure(disabledforeground="#bfbfbf")
        Popupmenu3.configure(foreground="#0080ff")
        Popupmenu3.post(event.x_root, event.y_root)

    @staticmethod
    def popup4(event, *args, **kwargs):
        Popupmenu4 = tk.Menu(root, tearoff=0)
        Popupmenu4.configure(activebackground="#ececec")
        Popupmenu4.configure(activeborderwidth="1")
        Popupmenu4.configure(activeforeground="#0080ff")
        Popupmenu4.configure(background="#ffffff")
        Popupmenu4.configure(borderwidth="1")
        Popupmenu4.configure(disabledforeground="#bfbfbf")
        Popupmenu4.configure(foreground="#0080ff")
        Popupmenu4.add_command(
                label="NewCommand")
        Popupmenu4.add_command(
                label="NewCommand")
        Popupmenu4.post(event.x_root, event.y_root)

if __name__ == '__main__':
    vp_start_gui()





